### ISSUE TITLE
Use the GitHub OIDC provider in AWS, via CDK, in just-a-table

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/just-a-table#1]
Maybe with https://www.npmjs.com/package/aws-cdk-github-oidc, maybe with https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.CfnOIDCProvider.html.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Use Cfn in my OIDC account-setup repo (https://github.com/VerticalRelevance/aws-github-oidc/issues/2)
- [ ] Use my OIDC repo to successfully OIDC-bootstrap two accounts
- [ ] Use my OIDC repo successfully against a repo that has already been bootstrapped
- [ ] Update OIDC repo README (https://github.com/VerticalRelevance/aws-github-oidc/issues/1)
- [ ] Make sure the desired deploy role name is in Actions vars before proceeding. This might not be too critical in the main and feature-branch Actions, since if the var is missing, the ARN of deployer role will be invalid.
- [ ] Make running oidc create a provider.
- [ ] Make main and feature-branch tell you what to do if auth fails.
- [ ] Use [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials).
- [ ] Check the trust policy to make sure only the desired repo can deploy. Do I need one role per repo?

**Comment by douglasnaphas** [comment]
I was thinking about having a separate repo like "set-up-aws-account" or even "set-up-github-aws-oidc," where the provider would be created, since it can happen only once per account.

However, I think I will keep the OIDC setup in each repo.

Lab accounts, the only case where multiple repos should be hitting the account, probably, are the exceptional case.

In most cases I want one repo to be the only one hitting the account.

**Comment by douglasnaphas** [comment]
If there's already a provider, it should...

**Comment by douglasnaphas** [comment]
If there's already a role with the desired name, it should...

**Comment by douglasnaphas** [comment]
I'm currently leaning towards one deploy role per repo.

I don't think leaving the role name unspecified is viable, because it has to be known in advance so that it can appear in the usage of [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) like in [this example](https://github.com/aripalo/aws-cdk-github-oidc#github-actions-workflow).

**Comment by douglasnaphas** [comment]
Do I want to automate the name of the deploy role, like I do with stackname?

I think I do. And I think I want it to vary with the repo owner and name, but not the branch.

That aligns with the [props required by `GithubActionsRole`](https://github.com/aripalo/aws-cdk-github-oidc#defining-a-role-for-github-actions-workflow-to-assume).

**Comment by douglasnaphas** [comment]
[This](https://docs.github.com/en/actions/learn-github-actions/variables#passing-values-between-steps-and-jobs-in-a-workflow) is what I need to do. I need to set the role in one step, probably by running a file in the repo called like `roleName.ts`, and then pull the role name from a variable when using `aws-actions/configure-aws-credentials`.

**Comment by douglasnaphas** [comment]
https://github.com/cdk-turnkey/just-a-bucket2/commit/c39e653e2a654dc36496432301668af19d61541b shows how I can place values computed in one step in the `with` of a later step.

I'll use this to compute my role name, which will vary with the owner and repo name.

**Comment by douglasnaphas** [comment]
I'm leaning towards a process where you run the oidc Action once right after you fork a repo or deploy from a template.

The oidc Action will need creds (access key id, secret access key, and session token) grabbed from the IAM Identity Center login screen.

The role the oidc Action assumes, though, will not necessarily need to be admin. What will it need to do? Check its own perms to make sure it's not over-permissioned? Annoying... Create a role? Create a provider? Practically speaking, it's probably going to be admin whenever I use it. But it would be great to figure out minimal perms.

**Comment by douglasnaphas** [comment]
I don't think the OIDC provider should live in an app-specific stack.

There can only be one provider per account.

We don't want to delete it just because we're deleting whatever the first app to use it was.

One bin/, two stacks.

Two stacks are needed:
1. One stack with the provider, where bin/ figures out whether or not a provider is needed. If there already is an OIDC provider, it doesn't get instantiated. Need to make sure the provider sticks around on app deletion.
2. One stack with the role that takes the rolename and I guess the provider ARN as inputs.

**Comment by douglasnaphas** [comment]
Actually app-specific CDK repos should probably not instantiate the OIDC provider. I should have one clean repo that does that once per account. App repos should then fail and refer you to the OIDC provider repo if the OIDC provider isn't present.

**Comment by douglasnaphas** [comment]
I'll deploy the OIDC provider, once per AWS account, from https://github.com/cirrus-duplicatus/aws-github-provider, or maybe https://github.com/VerticalRelevance/aws-github-oidc. All from the same repo (right?), accomplished by changing creds.

**Comment by douglasnaphas** [comment]
Progressing on this under https://github.com/VerticalRelevance/aws-github-oidc/issues/2.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Get a feel for CA thumpbrints

**Comment by douglasnaphas** [comment]
Maybe I don't have to worry about thumbprints at all. Maybe I can put literally the string `anything`, or `any-arbitrary-string` for the thumbprint. That's based on [this](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateOpenIDConnectProvider.html):

> Note
> AWS secures communication with some OIDC identity providers (IdPs) through our library of trusted root certificate authorities (CAs) instead of using a certificate thumbprint to verify your IdP server certificate. These OIDC IdPs include Auth0, GitHub, Google, and those that use an Amazon S3 bucket to host a JSON Web Key Set (JWKS) endpoint. In these cases, your legacy thumbprint remains in your configuration, but is no longer used for validation.

What happens if I use `anything` as the thumbprint? Will validation fail?

**Comment by douglasnaphas** [comment]
I'm using it just fine in Cabana and Hat Game. De-prioritizing.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Set up something with Actions Secrets and Variables to record in Variables the account number, and check against it with an Action step. I currently have no idea in what account and region my apps are running, and it's chaos.
